/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 bumi.gltf 
Author: Jacobs Development (https://sketchfab.com/Jacobs_Development)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-planet-earth-7b1dc4f802a54a6297e7a46888a85f77
Title: Low Poly Planet Earth
*/

import React, { useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useSpring, a } from "@react-spring/three";
import Plane from "./Plane";
import Cloudmap from "../textures/texture_cloud_8k.jpg";
import * as THREE from "three";
import {TextureLoader} from "three";
import { useLoader } from "@react-three/fiber";

const LON_OFFSET = -Math.PI / 2

export default function Bumi({ marker }) {
  const [isZoom, setIsZoom] = useState(false);

  const cloudMap = useLoader(TextureLoader,Cloudmap);

  const { lat, lon } = marker;

  const latRot = (lat * Math.PI / 180 )
  const lonRot = -(lon * Math.PI / 180) + LON_OFFSET

  const { nodes, materials } = useGLTF("/bumi.gltf");

  const { scale, markerPosition, rotation } = useSpring({
    scale: isZoom ? 2 : 1,
    markerPosition: isZoom ? [ 0, 0, 4.5] : [ 0, 0, 2.5],
    rotation: [latRot, lonRot, 0]
  })

  return (

    <>
      <a.group
        scale={scale}
        dispose={null}
        rotation={rotation}
        onClick={() => {
          setIsZoom(!isZoom);
          console.log(markerPosition);
        }}
      >
        <group scale={2}>
        <mesh
          geometry={nodes.Object_Planet_0.geometry}
          material={materials.Planet}
          rotation={[Math.PI+0.17, Math.PI+0.1, Math.PI]}
        />
        {/* <mesh>
          <sphereGeometry args={[1.5, 32, 32]} />
          <meshPhongMaterial
          map={cloudMap}
          opacity={0.2}
          depthWrite={true}
          transparent={true}
          side={THREE.DoubleSide} />
        
        </mesh> */}
        </group>
      </a.group>
      <Plane position={markerPosition} />
    </>
  );
}

useGLTF.preload("/bumi.gltf");
